name: 'Setup'
description: 'Setup the environment'

runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Create wrapper
      shell: 'sh'
      run: gradle wrapper


    # Make gradlew executable
    - name: Make gradlew executable
      shell: 'sh'
      run: sudo chmod +x ./gradlew

    # Necessary to build project
    - name: Create local.properties
      shell: 'sh'
      run: |
        echo "sdk.dir=$HOME/android-sdk" > local.properties
        chmod 644 local.properties
        echo "Created local.properties with SDK path: $HOME/android-sdk"
        cat local.properties