name: 'Setup'
description: 'Setup the environment'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      shell: bash
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        mkdir -p /root/.android/cmdline-tools/
        mv cmdline-tools /root/.android/cmdline-tools/latest
        export ANDROID_HOME=/root/.android
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-${{ 33 }}" "build-tools;${{ '33.0.0' }}"

    # Check if wrapper exists
    - name: Check Gradle Wrapper
      shell: bash
      id: wrapper-check
      run: |
        if [ ! -f "./gradlew" ]; then
          echo "Gradle wrapper not found, creating it"
          mkdir -p gradle/wrapper
          touch gradle/wrapper/gradle-wrapper.properties
          touch gradle/wrapper/gradle-wrapper.jar
          touch gradlew
          touch gradlew.bat
        fi

    # Make gradlew executable
    - name: Make gradlew executable
      shell: bash
      run: chmod +x ./gradlew

    # Initialize wrapper if needed
    - name: Initialize Gradle Wrapper
      shell: bash
      run: |
        if [ ! -f "./gradle/wrapper/gradle-wrapper.jar" ]; then
          ./gradlew wrapper
        fi

    - name: Create local.properties
      shell: bash
      run: echo "sdk.dir=/root/.android" > local.properties

    - name: Make gradlew executable
      shell: bash
      run: chmod +x ./gradlew