name: 'Setup'
description: 'Setup the environment'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      shell: 'sh'
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        mkdir -p $HOME/android-sdk/cmdline-tools/
        mv cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        chmod +x $ANDROID_HOME/cmdline-tools/latest/bin/*
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"
    

    # Check if wrapper exists
    - name: Check Gradle Wrapper
      shell: 'sh'
      id: wrapper-check
      run: |
        wget -q https://services.gradle.org/distributions/gradle-8.13-bin.zip
        unzip -q gradle-8.13-bin.zip
        export GRADLE_HOME=$PWD/gradle-8.13
        export PATH=$GRADLE_HOME/bin:$PATH
        
        if [ ! -f "./gradlew" ]; then
          echo "Gradle wrapper not found, generating it"
          gradle wrapper
        else
          echo "Gradle wrapper already exists"
        fi


    # Make gradlew executable
    - name: Make gradlew executable
      shell: 'sh'
      run: sudo chmod +x ./gradlew

    - name: Create local.properties
      shell: 'sh'
      run: |
        echo "sdk.dir=$HOME/android-sdk" > local.properties
        chmod 644 local.properties
        echo "Created local.properties with SDK path: $HOME/android-sdk"
        cat local.properties